version: "3.7"

services:
    app:
        image: thanhlongb/asm1
        volumes:
            - asm1-src:/var/www/html
        environment: 
            APP_ENV: local
            APP_KEY: 10txj(mO]wZm+>h%9}p<
            APP_DEBUG: 0
            LOG_CHANNEL: stackdriver
            APP_STORAGE: /tmp
            STORAGE_DIR: /tmp
            VIEW_COMPILED_PATH: /tmp
            CACHE_DRIVER: database
            SESSION_DRIVER: database
            # cloud related envs
            CLOUD_BUCKET_ID: rmit-gc-week2b
            CLOUD_PROJECT_ID: rmit-gc
            CLOUD_KEY_FILE: ../key.json
            LOCAL_DATA_FILE: /tmp/employees.csv
            CLOUD_DATA_FILE: employees.csv

    webserver:
        image: nginx:1.17-alpine
        ports:
            - "8001:80"      
        volumes:
            - asm1-src:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
    asm1-src: